config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  root to: 'user_sessions#index'
  resources :user_sessions, only: [:index, :create, :destroy]
  resources :top
  resources :checksheets do
    collection { get 'ict_1'}
    collection { get 'ict_2'}
    collection { get 'ict_3'}
    collection { get 'guidance_1'}
    collection { get 'guidance_2'}
    collection { get 'guidance_3'}
    collection { get 'health_1'}
    collection { get 'health_2'}
    collection { get 'health_3'}
  end
  resources :categories, shallow: true do
    resources :videos
    resources :questionnaires, only: [:index]
  end
  resources :comments
  resources :questionnaire_answers

  resources :last_questionnaire_answers, controller: :questionnaire_answers

  get 'text' => 'top#text'
  get 'questionnaire' => 'top#questionnaire'
  get 'last_questionnaire' => 'questionnaires#last_index'
  # get 'elearning_manual.pdf' => 'top#elearning_manual'

  get 'mypage' => 'users#mypage'

  get 'login' => 'user_sessions#create', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'checksheet_answers/draft'

  get 'video' => 'videos#video'

  namespace :api do
    post 'questionnaire_answers/draft'
    post 'last_questionnaire_answers/draft'
  end

  post 'self_checks/save'

  namespace :admin do
    resources :categories, shallow: true do
      resources :questionnaires
      resources :videos
    end
    resources :category_types
    resources :categories
    resources :top
    resources :csv_export, only: [:index]
    get 'csv_export_progress_checksheet' => 'csv_export#progress_checksheet'
    get 'csv_export_questionnaire' => 'csv_export#questionnaire'
  end
end

app/models/checksheet.rb
class Checksheet < ApplicationRecord 
  validates :question, presence: true
  validates :answer_type, presence: true

  has_many :video_checksheets
  has_many :videos, through: :video_checksheets

  def is_radio?
    self.answer_type === "radio"
  end

  def is_checkbox?
    self.answer_type === "checkbox"
  end

  def is_freedom?
    self.answer_type === "freedom"
  end

  def is_correct?(answer)
    if is_radio?
      return correct === answer
    elsif is_checkbox?
      return correct.split(",") === answer
    else
      if answer.strip.blank?
        return false
      end
      return true
    end
  end

  def get_choice(index)
    case index
    when 1
      self.choice_a
    when 2
      self.choice_b
    when 3
      self.choice_c
    when 4
      self.choice_d
    end
  end
end

app/controllers/checksheets_controller.rb
class ChecksheetsController < ApplicationController
  before_action :set_checksheet, only: [:create]

  def index
    @video = Video.find(params[:video_id])
    category_id = @video[:category_id]
    @category = Category.find(category_id)

    answered_all_checksheet?

    if @need_questionnaire && @video.order == 3
      set_result(2)
    end

    @checksheet_answer = ChecksheetAnswer.find_by(user_id: current_user.id, video_id: params[:video_id])
    if @video.order != 1
      videos = Video.where(category_id: category_id).order(:order)
      videos.each do |video|
        if video.order < @video.order
          answer = ChecksheetAnswer.find_by(user_id: current_user.id, video_id: video.id)
          if answer.nil? || !answer.correct_answer
            redirect_to "/categories/#{category_id}/videos"
            return
          end
        end
      end
    end

    if !@video.watched?(current_user)
      redirect_to "/videos/#{@video.id}"
      return
    end

    set_checksheet
    create_breadcrumbs
  end

  def create

    is_correct = true
    is_allfree = true

    answer = params["answer"] || {}

    @checksheets.each_with_index do |checksheet, index|
      is_correct &= checksheet.is_correct?(answer["#{checksheet.answer_type}#{index}"])
      is_allfree &= checksheet.is_freedom?
    end

    @need_questionnaire = false

    # 今回の結果を保存する
    checksheet_answer = ChecksheetAnswer.find_by(user_id: current_user.id, video_id: @video.id)
    checksheet_answer = ChecksheetAnswer.new(user_id: current_user.id, video_id: @video.id) if checksheet_answer.nil?

    checksheet_answer.answer = answer
    checksheet_answer.correct_answer |= is_correct

    checksheet_answer.save

    @checksheet_answer = checksheet_answer

    answered_all_checksheet?

    if is_correct
      set_result(@need_questionnaire ? 2 : 1)
    else
      set_result(is_allfree ? 4 : 3)
    end

    create_breadcrumbs
    render action: 'index'
  end

  private

  def create_breadcrumbs
    @video ||= Video.find_by(id: params[:video_id])

    @breadcrumbs = []
    @breadcrumbs << ['TOP', '/top']
    @breadcrumbs << ['講座一覧', categories_path]
    @breadcrumbs << ['初任者研修講座', categories_path]
    @breadcrumbs << [@chapter_title, video_path(@video)]
    @breadcrumbs << ['チェックシート', "/checksheets?video_id=#{@video.id}" ]
  end

    def set_checksheet
      @video = Video.find(params[:video_id])
      category_id = @video[:category_id]
      @category = Category.find(category_id)
      video_checksheets = VideoChecksheet.where(video_id: @video.id).order(:order)
      @checksheets = []
      video_checksheets.each do |video_checksheet|
        @checksheets << Checksheet.find(video_checksheet.checksheet_id)
      end

      @chapter_number = "#{(9 - @video.id) % 3 + 1}"
      @chapter_title = @video.title
      if category_id == 1
        @chapter_type = 'チャプター'
      elsif category_id == 2
        @chapter_type = 'チャプター'
      else
        @chapter_type = '研修項目'
      end
    end

    def set_result(result)
      case result
      when 1
        @result_text_1 = '次のチャプターへ進むことができます。'
        @result_text_2 = 'すべてのチャプターの終了後、初任者研修講座に関するアンケートを記入して、提出してください。'
        @result_link_text = 'チャプター一覧'
        @result_link = "/categories/#{@category.id}/videos"
        @is_correct = true
      when 2
        @result_text_1 = 'アンケートへ進むことができます。'
        @result_text_2 = 'すべてのチャプターが終了しました、初任者研修講座に関するアンケートを記入して、提出してください。'
        @result_link_text = 'アンケートへ'
        @result_link = "/categories/#{@category.id}/questionnaires"
        @is_correct = true
      when 3
        @result_text_1 = '未記入またはチェック内容が適切でない箇所があります。'
        @result_text_2 = '　チェック内容が全て適切ならば次のチャプターへ進むことができます。未記入箇所があった場合やチェック内容が適切でない箇所があった場合は、チャプターを終了することができず、次へ進むことができません。「動画視聴ページ戻る」ボタンをクリックし、動画を視聴するか、チェックシートをもう一度やり直してください。'
        @result_link_text = '動画視聴ページに戻る'
        @result_link = "/videos/#{@video.id}"
      when 4
        @result_text_1 = '記入されていない箇所があります。'
        @result_text_2 = '　記入されていない箇所がある場合は、チェックシートは送信できません。全て記入して送信してください。送信が完了すれば次のチャプターへ進むことができます。'
        @result_link_text = 'チャプター一覧'
        @result_link = "/categories/#{@category.id}/videos"
      else
        @result_text_1 = '未記入またはチェック内容が適切でない箇所があります。'
        @result_text_2 = '　チェック内容が全て適切ならば次のチャプターへ進むことができます。未記入箇所があった場合やチェック内容が適切でない箇所があった場合は、チャプターを終了することができず、次へ進むことができません。「動画視聴ページ戻る」ボタンをクリックし、動画を視聴するか、チェックシートをもう一度やり直してください。'
        @result_link_text = 'チャプター一覧'
        @result_link = "/categories/#{@category.id}/videos"
      end

    end

    def answered_all_checksheet?
      @videos = Video.where(category: @category)
      correct_count = 0
      @videos.each do |video|
        checksheet_answer = ChecksheetAnswer.find_by(user_id: current_user.id, video_id: video.id)
        if checksheet_answer.nil?
          next
        end
        if checksheet_answer.correct_answer
          correct_count += 1
        end
      end
      @need_questionnaire = correct_count === @videos.length
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checksheet_params
      params.require(:checksheet).permit(:question, :choice_a, :choice_b, :choice_c, :choice_d, :answer_type, :correct)
    end
end

app/helpers/checksheets_helper.rb
module ChecksheetsHelper
end

app/views/checksheets/health_1.html.erb
<div class="area-breadcrumb">
  <ul class="breadcrumb">
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/top" itemprop="url"><span itemprop="title">TOP</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/categories" itemprop="url"><span itemprop="title">講座一覧</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/categories/1/videos" itemprop="url"><span itemprop="title">初任者研修講座「情報教育と情報モラル」</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="" itemprop="url"><span itemprop="title"><%= @chapter_title %></span></a></li>
    <li class="current" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a class="current" href="" itemprop="url"><span itemprop="title">チェックシート</span></a></li>
  </ul>
</div>
<h1 class="headChecksheet"><span>チェックシート</span></h1>
<main class="wrap-checksheet">
  <section>
    <div class="heading-border">
      <p class="bold">「健康教育」</p>
      <p>－学校保健・学校安全・食育－</p>
    </div>
    <h2><span>確認項目<%= @chapter_number %></span><p><%= @chapter_title %></p></h2>

    <ol class="area-question">
      <%= form_tag checksheets_path(anchor: 'post-anchor'), method: :post do %>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q1</p>
            <p class="first-half"><%= @checksheet_1.question %></p>
          </dt>
          <dd class="answer">
            <textarea class="textbox" name="choice_1"></textarea>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q2</p>
            <p class="first-half"><%= @checksheet_2.question %><br></p>
          </dt>
          <dd class="answer">
            <textarea class="textbox" name="choice_2"></textarea>
          </dd>
        </dl>
      </li>
      <% if @chapter_number === 3 %>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q3</p>
            <p class="first-half"><%= @checksheet_3.question %><br></p>
          </dt>
          <dd class="answer">
            <textarea class="textbox" name="choice_3"></textarea>
          </dd>
        </dl>
      </li>
      <% end %>
    <div class="end">
      <div class="box">
        <div class="actions">
          <%= submit_tag '送信', class: "submit" %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= hidden_field_tag :checksheet_1, @checksheet_1.id %>
      <%= hidden_field_tag :checksheet_2, @checksheet_2.id %>
      <% if @chapter_number === 3 %>
      <%= hidden_field_tag :checksheet_3, @checksheet_3.id %>
      <% end %>
      <%= hidden_field_tag :chapter_number, @chapter_number %>
      <%= hidden_field_tag :category_id, @category_id %>
    </div>
  <% end %>
    </ol>
  </section>
</main>
<% if @result_text_1 %>
<div class="area-result">
  <a style="pointer-events: none;" name="post-anchor"><h3><%= @result_text_1 %></h3></a>
  <%= simple_format(@result_text_2,  class: @is_correct ? "tx-correct" : "") %>
  <div class="btn<%= ' btn-disable' if !@is_correct %>"><%= link_to @result_link_text, @result_link %></div>
</div>
<% end %>

app/views/checksheets/ict_1.html.erb
<div class="area-breadcrumb">
  <ul class="breadcrumb">
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/top" itemprop="url"><span itemprop="title">TOP</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/categories" itemprop="url"><span itemprop="title">講座一覧</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/categories/1/videos" itemprop="url"><span itemprop="title">初任者研修講座「情報教育と情報モラル」</span></a></li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="" itemprop="url"><span itemprop="title"><%= @chapter_title %></span></a></li>
    <li class="current" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a class="current" href="" itemprop="url"><span itemprop="title">チェックシート</span></a></li>
  </ul>
</div>
<h1 class="headChecksheet"><span>チェックシート</span></h1>
<main class="wrap-checksheet">
  <section>
    <div class="heading-border">
      <p class="bold">「情報教育と情報モラル」</p>
    </div>
    <h2><span>チャプター<%= @chapter_number %></span><p><%= @chapter_title %></p></h2>

    <ol class="area-question">
      <%= form_tag checksheets_path(anchor: 'post-anchor'), method: :post do %>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q1</p>
            <p class="first-half"><%= @checksheet_1.question %></p>
          </dt>
          <% if @chapter_number === 1 %>
          <dd class="answer">
            <input type="radio" name="choice_1" id="select1" value="1">
            <label for="select1"><%= @checksheet_1.choice_a %></label>
            <input type="radio" name="choice_1" id="select2" value="2">
            <label for="select2"><%= @checksheet_1.choice_b %></label>
            <input type="radio" name="choice_1" id="select3" value="3">
            <label for="select3"><%= @checksheet_1.choice_c %></label>
            <input type="radio" name="choice_1" id="select4" value="4">
            <label for="select4"><%= @checksheet_1.choice_d %></label>
          </dd>
          <% else %>
          <dd class="answerbox">
            <input type="checkbox" name="choice_1[]" id="select1" value="1">
            <label for="select1"><%= @checksheet_1.choice_a %></label>
            <input type="checkbox" name="choice_1[]" id="select2" value="2">
            <label for="select2"><%= @checksheet_1.choice_b %></label>
            <input type="checkbox" name="choice_1[]" id="select3" value="3">
            <label for="select3"><%= @checksheet_1.choice_c %></label>
            <input type="checkbox" name="choice_1[]" id="select4" value="4">
            <label for="select4"><%= @checksheet_1.choice_d %></label>
          </dd>
          <% end %>
        </dl>
      </li>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q2</p>
            <p class="first-half"><%= @checksheet_2.question %><br></p>
          </dt>
          <dd class="answerbox">
            <input type="checkbox" name="choice_2[]" id="select5" value="1">
            <label for="select5"><%= @checksheet_2.choice_a %></label>
            <input type="checkbox" name="choice_2[]" id="select6" value="2">
            <label for="select6"><%= @checksheet_2.choice_b %></label>
            <input type="checkbox" name="choice_2[]" id="select7" value="3">
            <label for="select7"><%= @checksheet_2.choice_c %></label>
            <input type="checkbox" name="choice_2[]" id="select8" value="4">
            <label for="select8"><%= @checksheet_2.choice_d %></label>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q3</p>
            <p class="first-half"><%= @checksheet_3.question %></p>
          </dt>
          <% if @chapter_number === 1 %>
          <dd class="answer">
            <input type="radio" name="choice_3" id="select9" value="1">
            <label for="select9"><%= @checksheet_3.choice_a %></label>
            <input type="radio" name="choice_3" id="select10" value="2">
            <label for="select10"><%= @checksheet_3.choice_b %></label>
            <input type="radio" name="choice_3" id="select11" value="3">
            <label for="select11"><%= @checksheet_3.choice_c %></label>
            <input type="radio" name="choice_3" id="select12" value="4">
            <label for="select12"><%= @checksheet_3.choice_d %></label>
          </dd>
          <% else %>
          <dd class="answerbox">
            <input type="checkbox" name="choice_3[]" id="select9" value="1">
            <label for="select9"><%= @checksheet_3.choice_a %></label>
            <input type="checkbox" name="choice_3[]" id="select10" value="2">
            <label for="select10"><%= @checksheet_3.choice_b %></label>
            <input type="checkbox" name="choice_3[]" id="select11" value="3">
            <label for="select11"><%= @checksheet_3.choice_c %></label>
            <input type="checkbox" name="choice_3[]" id="select12" value="4">
            <label for="select12"><%= @checksheet_3.choice_d %></label>
          </dd>
          <% end %>
        </dl>
      </li>
    <div class="end">
      <div class="box">
        <div class="actions">
          <%= submit_tag '送信', class: "submit" %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= hidden_field_tag :checksheet_1, @checksheet_1.id %>
      <%= hidden_field_tag :checksheet_2, @checksheet_2.id %>
      <%= hidden_field_tag :checksheet_3, @checksheet_3.id %>
      <%= hidden_field_tag :chapter_number, @chapter_number %>
      <%= hidden_field_tag :category_id, @category_id %>
    </div>
  <% end %>
    </ol>
  </section>
</main>
<% if @result_text_1 %>
<div class="area-result">
  <a style="pointer-events: none;" name="post-anchor"><h3><%= @result_text_1 %></h3></a>
  <%= simple_format(@result_text_2,  class: @is_correct ? "tx-correct" : "") %>
  <div class="btn"><%= link_to @result_link_text, @result_link %></div>
</div>
<% end %>

app/views/checksheets/index.html.erb
<% @page_title = "チェックシートページ#{@category.title}" %>

<main class="wrap-checksheet">
  <%= render 'shared/breadcrumbs', breadcrumbs: @breadcrumbs %>
  <h1 class="headChecksheet"><span>チェックシート</span></h1>
  <section>
    <div class="heading-border">
      <p class="bold"><%= @category.title %></p>
      <p><%= @category.format_short_description('') %></p>
    </div>
    <h2><span><%= @chapter_type + @chapter_number %></span><p><%= @video.title %></p></h2>

    <%= form_tag checksheets_path(anchor: 'post-anchor'), method: :post do %>
    <ol class="area-question">
      <% @checksheets.each_with_index do |checksheet, index| %>
      <% input_name = "answer[#{checksheet.answer_type}#{index}]" %>
      <% input_id = "select#{index}" %>
      <li>
        <dl>
          <dt class="question">
            <p class="number">Q<%= index + 1 %></p>
            <p class="first-half" style="width: 832px"><%= checksheet.question %></p>
          </dt>
          <% if checksheet.is_radio? %>
            <dd class="answer">
              <% for choice_index in 1..4 %>
                <% if checksheet.get_choice(choice_index).present? %>
                <% if @checksheet_answer.nil?
                  checked = ""
                else
                  checked = @checksheet_answer.is_checked?(checksheet.answer_type, index, choice_index) ? "checked" : ""
                end
                   %>
                  <input type="radio" name="<%= input_name %>" id="<%= "#{input_id}_#{choice_index}" %>" value="<%= choice_index %>" <%= checked %>>
                  <label for="<%= "#{input_id}_#{choice_index}" %>"><%= checksheet.get_choice(choice_index) %></label>
                <% end %>
              <% end %>
            </dd>
          <% elsif checksheet.is_checkbox? %>
            <dd class="answerbox">
              <% for choice_index in 1..4 %>
                <% if checksheet.get_choice(choice_index).present? %>
                <% if @checksheet_answer.nil?
                  checked = ""
                else
                  checked = @checksheet_answer.is_checked?(checksheet.answer_type, index, choice_index) ? "checked" : ""
                end
                   %>
                  <input type="checkbox" name="<%= input_name %>[]" id="<%= "#{input_id}_#{choice_index}" %>" value="<%= choice_index %>" <%= checked %>>
                  <label for="<%= "#{input_id}_#{choice_index}" %>"><%= checksheet.get_choice(choice_index) %></label>
                <% end %>
              <% end %>
            </dd>
          <% else %>
            <dd class="answer">
              <% if @checksheet_answer.nil?
                saved_text = ""
              else
                saved_text = @checksheet_answer.get_free_answer(index)
              end
              %>

              <textarea class="textbox" name="<%= input_name %>" id="<%= "freedom#{index}" %>"><%= saved_text %></textarea>
            </dd>
          <% end %>
        </dl>
      </li>
      <% end %>
    <div class="end">
      <div class="box">
        <div class="actions">
          <% if @checksheet_answer.present? && @checksheet_answer.correct_answer %>
          <div class="submit-disable">
            <p>送信済み</p>
          </div>
          <% else %>
          <%= submit_tag '送信', class: "submit" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= hidden_field_tag :chapter_number, @chapter_number %>
      <%= hidden_field_tag :video_id, @video.id %>
    </div>
  </ol>
  <% end %>
  </section>
  <% if @result_text_1 %>
  <div class="area-result">
    <a style="pointer-events: none;" name="post-anchor"><h3><%= @result_text_1 %></h3></a>
    <%= simple_format(@result_text_2,  class: @is_correct ? "tx-correct" : "") %>
    <div class="btn"><%= link_to @result_link_text, @result_link %></div>
  </div>
  <% end %>
</main>

<% if @result_text_1.nil? %>
<script type="text/javascript">
  $(function() {
    setInterval(function() {

      var param = {};

      <% @checksheets.each_with_index do |checksheet, index| %>
        <% if checksheet.is_radio? %>
          var key = "<%= "radio#{index}" %>";
          var value = $("[name='answer[<%= "radio#{index}" %>]']:checked").val();
          if (value != null) {
            param[key] = value;
          }
        <% elsif checksheet.is_checkbox? %>
          var key = "<%= "checkbox#{index}" %>";
          param[key] = [];
          $("[name='answer[<%= "checkbox#{index}" %>][]']:checked").each(function() {
            var value = this.value;
            if (value != null) {
              param[key].push(value);
            }
          });
        <% else %>
          var key = "<%= "freedom#{index}" %>";
          var value = $("#<%= "freedom#{index}" %>").val();
          if (value != null) {
            param[key] = value;
          }
        <% end %>
      <% end %>
      $.post("/checksheet_answers/draft", {
        'user_id': <%= current_user.id %>,
        'video_id': <%= @video.id %>,
        'answer': param
      }, function(data){
      });
    }, 10000)
  });

</script>
<% end %>