config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  root to: 'user_sessions#index'
  resources :user_sessions, only: [:index, :create, :destroy]
  resources :top
  resources :checksheets do
    collection { get 'ict_1'}
    collection { get 'ict_2'}
    collection { get 'ict_3'}
    collection { get 'guidance_1'}
    collection { get 'guidance_2'}
    collection { get 'guidance_3'}
    collection { get 'health_1'}
    collection { get 'health_2'}
    collection { get 'health_3'}
  end
  resources :categories, shallow: true do
    resources :videos
    resources :questionnaires, only: [:index]
  end
  resources :comments
  resources :questionnaire_answers

  resources :last_questionnaire_answers, controller: :questionnaire_answers

  get 'text' => 'top#text'
  get 'questionnaire' => 'top#questionnaire'
  get 'last_questionnaire' => 'questionnaires#last_index'
  # get 'elearning_manual.pdf' => 'top#elearning_manual'

  get 'mypage' => 'users#mypage'

  get 'login' => 'user_sessions#create', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'checksheet_answers/draft'

  get 'video' => 'videos#video'

  namespace :api do
    post 'questionnaire_answers/draft'
    post 'last_questionnaire_answers/draft'
  end

  post 'self_checks/save'

  namespace :admin do
    resources :categories, shallow: true do
      resources :questionnaires
      resources :videos
    end
    resources :category_types
    resources :categories
    resources :top
    resources :csv_export, only: [:index]
    get 'csv_export_progress_checksheet' => 'csv_export#progress_checksheet'
    get 'csv_export_questionnaire' => 'csv_export#questionnaire'
  end
end

app/models/category.rb
class Category < ApplicationRecord 
  validates :title, presence: true
  validates :short_description, presence: false
  validates :description, presence: false

  belongs_to :category_type
  has_many :questionnaires
  has_many :questionnaire_answers
  has_many :videos

  def format_short_description(replace)
    short_description.gsub(/,/, replace)
  end

  def questionnaire_complete?(user)
    user.questionnaire_answers.find_by(category: self).try(:post_completion)
  end

  def enable_questionnaire?(user)
    Video.where(category: self).each do |video|
      unless ChecksheetAnswer.find_by(user_id: user.id, video_id: video.id).try(:correct_answer)
        return false
      end
    end
    !questionnaire_complete?(user)
  end
end

app/models/category_type.rb
class CategoryType < ApplicationRecord
  validates :title, presence: true

  has_many :categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::Base
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(:id)
    @category_types = CategoryType.all.order(:id)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @text = '作成'
  end

  # GET /categories/1/edit
  def edit
    @text = '更新'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :short_description, :description, :category_type_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(:id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '講座名' %><br>
    <%= f.text_field :title %><br>
    <%= f.label 'カテゴリ' %><br>
    <%= f.collection_select :category_type_id, CategoryType.all, :id, :title, {}, style: 'width:150px' %><br>
    <%= f.label '説明' %><br>
    <%= f.text_area :short_description, size: '100x5' %><br>
  </div>
  <div class="actions">
    <%= f.submit @text, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>講座の編集</h1>

<%= render 'form' %>

<%= link_to "講座を削除", admin_category_path(@category), :method => :delete, :data => { :confirm => "削除してもよろしいですか？(削除後は取り消せません)" }, class: "btn btn-danger" %>

<%= link_to 'もどる', admin_categories_path, class: "btn btn-default" %>

app/views/admin/categories/index.html.erb
<h1>講座一覧</h1>

<div class='table-responsive'>
  <%= link_to "講座を追加", new_admin_category_path, class: "btn btn-primary" %><span style="margin-left: 20px">業者メンテナンス用です</span>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
          <td><%= link_to '編集', edit_admin_category_path(category) %></td>
          <td><%= link_to 'チャプター編集画面へ', admin_category_videos_url(category) %></td>
          <td><%= link_to 'アンケート設定画面へ', admin_category_questionnaires_url(category) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h1>講座カテゴリ一覧</h1>

<div class='table-responsive'>
  <%= link_to "カテゴリを追加", new_admin_category_type_path, class: "btn btn-primary" %><span style="margin-left: 20px">業者メンテナンス用です</span>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @category_types.each do |category_type| %>
        <tr>
          <td><%= category_type.title %></td>
          <td><%= link_to '編集', edit_admin_category_type_path(category_type) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<h1>講座の作成</h1>

<%= render 'form' %>

<%= link_to 'もどる', admin_categories_path, class: "btn btn-default" %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>