config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  root to: 'user_sessions#index'
  resources :user_sessions, only: [:index, :create, :destroy]
  resources :top
  resources :checksheets do
    collection { get 'ict_1'}
    collection { get 'ict_2'}
    collection { get 'ict_3'}
    collection { get 'guidance_1'}
    collection { get 'guidance_2'}
    collection { get 'guidance_3'}
    collection { get 'health_1'}
    collection { get 'health_2'}
    collection { get 'health_3'}
  end
  resources :categories, shallow: true do
    resources :videos
    resources :questionnaires, only: [:index]
  end
  resources :comments
  resources :questionnaire_answers

  resources :last_questionnaire_answers, controller: :questionnaire_answers

  get 'text' => 'top#text'
  get 'questionnaire' => 'top#questionnaire'
  get 'last_questionnaire' => 'questionnaires#last_index'
  # get 'elearning_manual.pdf' => 'top#elearning_manual'

  get 'mypage' => 'users#mypage'

  get 'login' => 'user_sessions#create', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'checksheet_answers/draft'

  get 'video' => 'videos#video'

  namespace :api do
    post 'questionnaire_answers/draft'
    post 'last_questionnaire_answers/draft'
  end

  post 'self_checks/save'

  namespace :admin do
    resources :categories, shallow: true do
      resources :questionnaires
      resources :videos
    end
    resources :category_types
    resources :categories
    resources :top
    resources :csv_export, only: [:index]
    get 'csv_export_progress_checksheet' => 'csv_export#progress_checksheet'
    get 'csv_export_questionnaire' => 'csv_export#questionnaire'
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord 
  validates :question, presence: true

  belongs_to :category

  def is_radio?
    self.question_type == "radio"
  end

  def is_checkbox?
    self.question_type == "checkbox"
  end

  def is_free?
    self.question_type == "free"
  end

  def get_question(index)
    case index
    when 1
      self.choice_a
    when 2
      self.choice_b
    when 3
      self.choice_c
    else
      self.choice_d
    end
  end
end

app/controllers/admin/questionnaires_controller.rb
class Admin::QuestionnairesController < Admin::Base
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    # @questionnaires = Questionnaire.all
    @category = Category.find(params[:category_id])
    @questionnaires = @category.questionnaires
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @category = Category.find(params[:category_id])
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @category = Category.find(params[:category_id])
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.category = @category

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to admin_category_questionnaires_path(@category), notice: 'Questionnaire was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to admin_category_questionnaires_path(@category), notice: 'Questionnaire was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to admin_category_questionnaires_path(@category), notice: 'Questionnaire was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
      @category = @questionnaire.category
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:category_id, :question)
    end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  def index
    @save_api = "/questionnaire_answers/draft"
    @category = Category.find(params[:category_id])
    @item_prop_title_1 = @category.title
    @item_prop_title_2 = "初任者研修講座に関するアンケート"
    @description = @category.format_short_description('')
    @questionnaires = Questionnaire.where(category: @category)
    @questionnaire_answer = QuestionnaireAnswer.where(category: @category, user: current_user).first || QuestionnaireAnswer.new

    create_breadcrumbs
  end

  def last_index
    @save_api = "/last_questionnaire_answers/draft"
    @item_prop_title_1 = ""
    @item_prop_title_2 = "ｅラーニングを活用した研修についてのアンケート"
    @description = ""
    @questionnaire_answer = LastQuestionnaireAnswer.where(user: current_user).first || LastQuestionnaireAnswer.new
    @questionnaires = [
      Questionnaire.new(
      question: "動画教材の閲覧や、教材のダウンロードなどの動作について、どう感じましたか。",
      choice_a: "①　満足である",
      choice_b: "②　やや満足である",
      choice_c: "③　少し不満である",
      choice_d: "④　不満である",
      question_type: "radio",
      order: 1
    ),

    Questionnaire.new(
      question: "問１で③、④を選択された方は、その理由をお答えください。（複数回答可）",
      choice_a: "①　今回のｅラーニングに限り、動画がなめらかに映し出されなかったから。",
      choice_b: "②　今回のｅラーニングに限り、教材のダウンロードに時間がかかったから。",
      choice_c: "③　その他",
      # ここ本来は選択肢3つだけの上に、3つめの選択肢は自由回答
      choice_d: "",
      question_type: "checkbox",
      order: 2
    ),

    Questionnaire.new(
      question: "今後もｅラーニングを利用した研修があれば受講したいと思いますか。",
      choice_a: "①　そう思う",
      choice_b: "②　ややそう思う",
      choice_c: "③　あまり思わない",
      choice_d: "④　思わない",
      question_type: "radio",
      order: 3
    ),

    Questionnaire.new(
      question: "問３で①、②を選択された方にお聞きします。今後、ｅラーニングを利用した研修として、どのような研修内容を望まれますか。",
      choice_a: "",
      choice_b: "",
      choice_c: "",
      choice_d: "",
      question_type: "free",
      order: 4
    ),

    Questionnaire.new(
      question: "問３で①、②を選択された方は、その理由をお答えください。（複数回答可）",
      choice_a: "①　どこにいても受講できるから",
      choice_b: "②　自分が受講したいときに受講できるから",
      choice_c: "③　重要だと思うところを繰り返して受講することができるから",
      choice_d: "④　その他", # 4つめの選択肢は自由回答
      question_type: "checkbox",
      order: 5
    ),

    Questionnaire.new(
      question: "問３で③、④を選択された方は、その理由をお答えください。（複数回答可）",
      choice_a: "①　パソコンやスマートフォンでの操作が難しいから",
      choice_b: "②　インターネットがつながる環境にいないことが多いから",
      choice_c: "③　教育研究所に出向いて受講したいから",
      choice_d: "④　その他", # 4つめの選択肢は自由回答
      question_type: "checkbox",
      order: 6
    ),

    Questionnaire.new(
      question: "今回のｅラーニングを利用した研修において、研修内容や操作方法などについて具体的な改善点を書いてください。",
      choice_a: "",
      choice_b: "",
      choice_c: "",
      choice_d: "",
      question_type: "free",
      order: 7
    ),

    Questionnaire.new(
      question: "今回のｅラーニングを利用した研修を受講した感想を書いてください。",
      choice_a: "",
      choice_b: "",
      choice_c: "",
      choice_d: "",
      question_type: "free",
      order: 8
    )
    ]

    create_breadcrumbs
    render action: :index
  end

  private

  def create_breadcrumbs
    @breadcrumbs = []
    @breadcrumbs << ['TOP', '/top']
    @breadcrumbs << ['講座一覧', categories_path]
    @breadcrumbs << ['初任者研修講座', categories_path]
    @breadcrumbs << [@item_prop_title_2, '']
  end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/admin/questionnaires/_form.html.erb
<%= form_for([:admin] + shallow_args(@category, @questionnaire)) do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question, size: '50x5' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/questionnaires/edit.html.erb
<h1>アンケート設問編集</h1>

<%= render 'form' %>

<%= link_to '削除', admin_questionnaire_path(@questionnaire), method: :delete, data: { confirm: '削除してもよろしいですか？(削除後は取り消せません)' }, class: 'btn btn-danger' %>
<%= link_to '戻る', admin_category_questionnaires_path(@category) %>

app/views/admin/questionnaires/index.html.erb
<h1>アンケート設問一覧</h1>

<div class='table-responsive'>
  <%= link_to '設問追加', new_admin_category_questionnaire_path(@category), class: 'btn btn-primary' %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>設問</th>
        <th>編集</th>
      </tr>
    </thead>

    <tbody>
      <% @questionnaires.each do |questionnaire| %>
        <tr>
          <td><%= questionnaire.question %></td>
          <td><%= link_to '編集', edit_admin_questionnaire_path(questionnaire) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/questionnaires/new.html.erb
<h1>アンケート設問追加</h1>

<%= render 'form' %>

<%= link_to '戻る', admin_category_questionnaires_path(@category) %>

app/views/admin/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>設問:</strong>
  <%= @questionnaire.question %>
</p>

<%= link_to '編集', edit_admin_questionnaire_path(@questionnaire) %> |
<%= link_to '戻る', admin_categories_path %>