config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  root to: 'user_sessions#index'
  resources :user_sessions, only: [:index, :create, :destroy]
  resources :top
  resources :checksheets do
    collection { get 'ict_1'}
    collection { get 'ict_2'}
    collection { get 'ict_3'}
    collection { get 'guidance_1'}
    collection { get 'guidance_2'}
    collection { get 'guidance_3'}
    collection { get 'health_1'}
    collection { get 'health_2'}
    collection { get 'health_3'}
  end
  resources :categories, shallow: true do
    resources :videos
    resources :questionnaires, only: [:index]
  end
  resources :comments
  resources :questionnaire_answers

  resources :last_questionnaire_answers, controller: :questionnaire_answers

  get 'text' => 'top#text'
  get 'questionnaire' => 'top#questionnaire'
  get 'last_questionnaire' => 'questionnaires#last_index'
  # get 'elearning_manual.pdf' => 'top#elearning_manual'

  get 'mypage' => 'users#mypage'

  get 'login' => 'user_sessions#create', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'checksheet_answers/draft'

  get 'video' => 'videos#video'

  namespace :api do
    post 'questionnaire_answers/draft'
    post 'last_questionnaire_answers/draft'
  end

  post 'self_checks/save'

  namespace :admin do
    resources :categories, shallow: true do
      resources :questionnaires
      resources :videos
    end
    resources :category_types
    resources :categories
    resources :top
    resources :csv_export, only: [:index]
    get 'csv_export_progress_checksheet' => 'csv_export#progress_checksheet'
    get 'csv_export_questionnaire' => 'csv_export#questionnaire'
  end
end

app/models/video.rb
class Video < ApplicationRecord 
  validates_presence_of :title
  validates_presence_of :description

  belongs_to :category
  has_many :comments
  has_many :progresses
  has_many :video_checksheets
  has_many :checksheets, through: :video_checksheets
  has_one :checksheet_answer

  has_attached_file :videofile
  validates_attachment :videofile, content_type: { content_type: ['video/mp4'] }

  has_attached_file :worksheet
  has_attached_file :slide

  has_attached_file :thumbnail, styles: { small: '320x320>' }
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/(png|jpeg|jpg)\z/

  validates :videofile, attachment_presence: true
  validates :thumbnail, attachment_presence: true
  validates :minutes, presence: true
  validates :seconds, presence: true

  validates :minutes, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :seconds, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 60 }

  def watched?(user)
    Progress.exists?(user: user, video: self)
  end

  def checksheet_answered?(user)
    ChecksheetAnswer.exists?(user: user, video: self)
  end

  def checksheet_complete?(user)
    ChecksheetAnswer.find_by(user: user, video: self).try(:correct_answer)
  end

  def videourl(category_id)
    return videofile.url if can_upload_file?

    # Heroku上でファイルアップロードできないがゆえの処理
    # 必要ならファイルをS3にホストしてvideofile.urlを返すようにする
    case category_id
    when 1
      case self.id
      when 3
        'http://test3.entaworks.co.jp/shinonome/videos/01_A.mp4'
      when 2
        'http://test3.entaworks.co.jp/shinonome/videos/01_B.mp4'
      when 1
        'http://test3.entaworks.co.jp/shinonome/videos/01_C.mp4'
      else
        'http://test3.entaworks.co.jp/shinonome/videos/01_A.mp4'
      end
    when 2
      case id
      when 6
        'http://test3.entaworks.co.jp/shinonome/videos/02_A.mp4'
      when 5
        'http://test3.entaworks.co.jp/shinonome/videos/02_B.mp4'
      when 4
        'http://test3.entaworks.co.jp/shinonome/videos/02_C.mp4'
      else
        'http://test3.entaworks.co.jp/shinonome/videos/02_A.mp4'
      end
    when 3
      case id
      when 9
        'http://test3.entaworks.co.jp/shinonome/videos/03.mp4'
      when 8
        'http://test3.entaworks.co.jp/shinonome/videos/04.mp4'
      when 7
        'http://test3.entaworks.co.jp/shinonome/videos/05.mp4'
      else
        'http://test3.entaworks.co.jp/shinonome/videos/03.mp4'
      end
    else
      'http://test3.entaworks.co.jp/shinonome/videos/01_A.mp4'
    end
  end

  def thumbnail_url(style = :original)
    return thumbnail.url(style) if can_upload_file?

    "imgChapterList_0#{id}.png"
  end

  def checksheeturl
    case self.id
    when 3
      '/checksheets/guidance_1'
    when 2
      '/checksheets/guidance_2'
    when 1
      '/checksheets/guidance_3'
    when 6
      '/checksheets/ict_1'
    when 5
      '/checksheets/ict_2'
    when 4
      '/checksheets/ict_3'
    when 9
      '/checksheets/health_1'
    when 8
      '/checksheets/health_2'
    when 7
      '/checksheets/health_3'
    else
      '/checksheets/guidance_1'
    end
  end

  def playtime
    min = minutes || 0
    sec = seconds || 0

    "#{min}分#{'%02d' % sec}秒"
  end

  def worksheeturl
    return worksheet.url if can_upload_file?

    'http://test3.entaworks.co.jp/shinonome/docs/ＩＣＴ_ワークシート.pdf'
  end

  def slideurl
    return slide.url if can_upload_file?

    'http://test3.entaworks.co.jp/shinonome/docs/1_0810教科等指導X.pdf'
  end

  def format_worksheet_file_size
    return Filesize.new(self.worksheet_file_size.to_s, Filesize::SI).pretty if can_upload_file?

    '227KB'
  end

  def format_slide_file_size
    return Filesize.new(self.slide_file_size.to_s, Filesize::SI).pretty if can_upload_file?

    '1.9MB'
  end

  def videofilename
    if videofile.present? && can_upload_file?
      ":#{videofile_file_name}"
    else
      ''
    end
  end

  def thumbnailfilename
    if thumbnail.present? && can_upload_file?
      ":#{thumbnail_file_name}"
    else
      ''
    end
  end

  def worksheetfilename
    unless have_worksheet?
      return ""
    end

    if worksheet.present? && can_upload_file?
      ":#{worksheet_file_name}"
    else
      ''
    end
  end

  def slidefilename
    unless have_slide?
      return ""
    end
    if slide.present? && can_upload_file?
      ":#{slide_file_name}"
    else
      ''
    end
  end

  def have_worksheet?
    worksheet.present?
  end

  def have_slide?
    slide.present?
  end

  private

  def can_upload_file?
    ENV['SHINONOME_FILE_UPLOAD_DISABLED'].nil?
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::Base
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @category = Category.find(params[:category_id])
    @videos = Video.where(category: @category)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @category = Category.find(params[:category_id])
    @video = Video.new
    @text = "作成"
  end

  # GET /videos/1/edit
  def edit
    @text = "更新"
  end

  # POST /videos
  # POST /videos.json
  def create
    @category = Category.find(params[:category_id])
    @video = Video.new(video_params)
    @video.category = @category

    respond_to do |format|
      if @video.save
        format.html { redirect_to admin_category_videos_url(@category), notice: 'Video was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to admin_category_videos_url(@category), notice: 'Video was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to admin_category_videos_url(@category), notice: 'Video was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
      @category = @video.category
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :videofile, :worksheet, :slide, :minutes, :seconds, :thumbnail)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  layout "ignore_layout", only: [:video]

  # GET /videos
  # GET /videos.json
  def index
    @category = Category.find(params[:category_id])
    @videos = Video.where(category: @category).order(:order)

    @breadcrumbs = []
    @breadcrumbs << ['TOP', '/top']
    @breadcrumbs << ['講座一覧', categories_path]
    @breadcrumbs << ['初任者研修講座']
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    @category = @video.category
    if @category.id === 3
      @chapter_text = '研修項目'
      @to_checksheet_text = '　動画を最後まで視聴した後、チェックシートに進んでください。記入されていない箇所がある場合は、チェックシートは送信できません。全て記入して送信してください。'
    else
      @chapter_text = 'チャプター'
      @to_checksheet_text = '　動画を最後まで視聴した後、チェックシートに進んでください。チェック内容がすべて適切ならば、このチャプターは終了です。未記入箇所があった場合やチェック内容が適切でない箇所があった場合は、チャプターを終了することができず、次へ進むことができません。「動画視聴ページに戻る」ボタンをクリックし、動画を視聴するか、チェックシートをもう一度やり直してください。'
    end
    @comments = @video.comments.includes(:user)
    @comment = Comment.new
    @current_user = current_user
  end

  # GET /video
  def video
    @video = Video.find(params[:video_id])
    @category = Category.find(@video.category.id)
    render action: 'video_iframe'
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.erb
<%= form_for([:admin] + shallow_args(@category, @video)) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'チャプター名' %>
    <%= f.text_field :title, size: '50' %><br>
    <%= f.label '説明' %><br>
    <%= f.text_area :description, size: '100x5' %><br>

    <%= f.label '動画ファイル' %>
    <%= f.file_field :videofile, style: "display:none;", onchange: "$('#fake_input_file_1').text($(this)[0].files[0].name)" %><br>
    <input type="button" value="ファイル選択" onClick="$('#video_videofile').click();">
    <span id="fake_input_file_1">
      <%= @video.videofile_file_name.nil? ? '選択されていません' : @video.videofile_file_name %>
    </span>
    <br>
    <br>

    <%= f.label '動画サムネイル画像' %>
    <%= f.file_field :thumbnail, style: "display:none;", onchange: "$('#fake_input_file_2').text($(this)[0].files[0].name)" %><br>
    <input type="button" value="ファイル選択" onClick="$('#video_thumbnail').click();">
    <span id="fake_input_file_2">
      <%= @video.thumbnail_file_name.nil? ? '選択されていません' : @video.thumbnail_file_name %>
    </span>
    <br>
    <br>

    <%= f.label '動画の長さ' %><br>
    <%= f.number_field :minutes, min: 0, step: 1 %><span>分</span>
    <%= f.number_field :seconds, min: 0, max: 59, step: 1 %><span>秒</span><br>
    <br>

    <%= f.label 'ワークシート' %>
    <%= f.file_field :worksheet, style: "display:none;", onchange: "$('#fake_input_file_3').text($(this)[0].files[0].name)" %><br>
    <input type="button" value="ファイル選択" onClick="$('#video_worksheet').click();">
    <span id="fake_input_file_3">
      <%= @video.worksheet_file_name.nil? ? '選択されていません' : @video.worksheet_file_name %>
    </span>
    <br>
    <br>

    <%= f.label 'スライド資料' %>
    <%= f.file_field :slide, style: "display:none;", onchange: "$('#fake_input_file_4').text($(this)[0].files[0].name)" %><br>
    <input type="button" value="ファイル選択" onClick="$('#video_slide').click();">
    <span id="fake_input_file_4">
      <%= @video.slide_file_name.nil? ? '選択されていません' : @video.slide_file_name %>
    </span>
    <br>
    <br>
  </div>
  <div class="actions">
    <%= f.submit @text, class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/videos/edit.html.erb
<h1>チャプターの編集</h1>

<%= render 'form' %>

<%= link_to "チャプターを削除", admin_video_path(@video), :method => :delete, :data => { :confirm => "削除してもよろしいですか？(削除後は取り消せません)" }, class: "btn btn-danger" %>

<%= link_to 'もどる', admin_category_videos_path(@category), class: "btn btn-default" %>

app/views/admin/videos/index.html.erb
<h1>チャプターの編集</h1>

<div class='table-responsive'>
  <%= link_to "チャプターの追加", new_admin_category_video_path(@category), class: "btn btn-primary" %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.title %></td>
          <td><%= link_to '編集', edit_admin_video_path(video) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/admin/videos/new.html.erb
<h1>チャプターの作成</h1>

<%= render 'form' %>

<%= link_to 'もどる', admin_category_videos_path(@category), class: "btn btn-default" %>

app/views/admin/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %><br>
  <strong>Description:</strong>
  <%= @video.description %><br>
  <strong>Videofile:</strong>
  <%= link_to 'プレビュー', @video.videofile.url %><br>
  <strong>Worksheet:</strong>
  <%= link_to 'プレビュー', @video.worksheet.url %><br>
  <strong>Slide:</strong>
  <%= link_to 'プレビュー', @video.slide.url %><br>
</p>

<%= link_to 'Edit', edit_admin_video_path(@video) %> |
<%= link_to 'Back', admin_categories_path %>